---
title: "Institutions, power, and inequality"
date: "2019-02-13"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required

***Important***: The PDFs of the North and Putnam chapters are posted on Learning Suite.

- <i class="fas fa-book"></i> Introduction and 5.1–5.10 in *Economy, Society, and Public Policy* [@core-espp]
- <i class="fab fa-twitter-square"></i> [Tweet by Jennifer Victor](https://twitter.com/jennifernvictor/status/1042181507480203264)
- <i class="fas fa-podcast"></i> Freakonomics Radio, ["Earth 2.0: What Would Our Economy Look Like?,"](http://freakonomics.com/podcast/earth-2-0-economics-edition-part-1/) April 12, 2017
- At least one of these episodes (both if you're adventurous):
    - <i class="fas fa-podcast"></i> Planet Money, ["The Dollar at the Center of the World,"](https://www.npr.org/sections/money/2014/07/16/331743569/episode-552-the-dollar-at-the-center-of-the-world) episode 553, July 16, 2014
    - <i class="fas fa-podcast"></i> Planet Money, ["Retraining Day,"](https://www.npr.org/sections/money/2017/01/27/512060753/episode-750-retraining-day) episode 750, January 27, 2017
- <i class="far fa-file-pdf"></i> Chapter 1 in Douglass C. North, *Institutions, Institutional Change, and Economic Performance* [@North:1990] (Remember to use your grad school reading skills here! Don't try to read every word!)
- <i class="far fa-file-pdf"></i> Chapter 6 in Robert D. Putnam, *Making Democracy Work: Civic Traditions in Modern Italy* [@Putnam:1994] (Remember to use your grad school reading skills here! Don't try to read every word!)
