---
title: "When governments go wrong + institutional alternatives"
date: "2019-03-27"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required

**Important**: This looks like a ton of reading, and there is a lot, but note that many of these things are shorter videos or tweets. Listen to the podcasts passively while doing other stuff, like driving or doing the dishes.

The materials in the institutional alternatives section are foundational to public administration economics and the whole reason the nonprofit sector is folded into the public sector in this program. They're long and old and stilted and full of math, so **please** don't spend an inordinate amount of time on them. Remember your grad school reading skills—read the introduction and conclusion, look around in the middle for things that look interesting, and make sure you understand the gist of what's going on.

## When governments go wrong

- <i class="fab fa-twitter-square"></i> [Noah Smith on why we should worry about race, culture, and politics when thinking about economics](https://twitter.com/noahpinion/status/946446862898282496)
- <i class="fab fa-youtube"></i> Adam Ruins Everything, ["The Disturbing History of the Suburbs"](https://www.youtube.com/watch?v=ETR9qrVS17g), October 4, 2017^[Yes, a CollegeHumor video. Seriously.]
- <i class="fas fa-external-link-square-alt"></i> Aaron Glantz and Emmanuel Martinez, ["Kept out: For people of color, banks are shutting the door to homeownership,"](https://www.revealnews.org/article/for-people-of-color-banks-are-shutting-the-door-to-homeownership/) Reveal, February 15, 2018
    - Alternatively, listen to the podcast version of this story, which goes in more depth and is really fantastic: <i class="fas fa-podcast"></i> ["The red line: Racial disparities in lending,"](https://www.revealnews.org/episodes/the-red-line-racial-disparities-in-lending/) Reveal, February 17, 2018
- <i class="fas fa-external-link-square-alt"></i> Emma Roller's interview with Mehrsa Baradaran, ["How the U.S. Government Locked Black Americans Out of Attaining the American Dream,"](https://splinternews.com/how-the-u-s-government-locked-black-americans-out-of-a-1819221197), *Splinter*, October 11, 2017^[[Mehrsa is LDS](https://en.wikipedia.org/wiki/Mehrsa_Baradaran), btw.]
- <i class="far fa-file-pdf"></i> Hamilton, et al., ["Umbrellas Don't Make it Rain: Why Studying and Working Hard Isn't Enough for Black Americans"](http://econ.hunter.cuny.edu/wp-content/uploads/2016/03/seminar2016-darity2.pdf) [@HamiltonDarityPrice:2015]
- <i class="fas fa-podcast"></i> This American Life, ["The Problem We All Live With, Part One,"](https://www.thisamericanlife.org/562/the-problem-we-all-live-with-part-one) episode 562, July 31, 2015
- <i class="fas fa-podcast"></i> This American Life, ["The Problem We All Live With, Part Two,"](https://www.thisamericanlife.org/563/the-problem-we-all-live-with-part-two) episode 563, August 7, 2015


## Institutional alternatives

***Important***: The PDFs of the articles and chapters are posted on Learning Suite.

- <i class="far fa-file-pdf"></i> Chapter 5 in Douglass C. North, *Institutions, Institutional Change, and Economic Performance* [@North:1990]
- <i class="far fa-file-pdf"></i> Olaf Corry, "Defining and Theorizing the Third Sector" [@Corry:2010]
- <i class="far fa-file-pdf"></i> Chapters 1 and 2 in Elinor Ostrom, *Governing the Commons: The Evolution of Institutions for Collective Action* [@Ostrom:1990]
    - This one is super long and game theoretical. You can skim through lots of it (especially the mathy sections). But it's also pretty foundational to public administration, so it *is* important. Make sure you get the gist of what's happening, but don't strain yourself with all the tiny details.


# Not required, but highly recommended

- <i class="fas fa-external-link-square-alt"></i> Destin Jenkins, ["Who Segregated America?,"](http://www.publicbooks.org/who-segregated-america/) *Public Books*, December 21, 2017
