---
title: "Evaluating policies"
date: "2019-04-10"
citeproc: false
bibliography: ../../static/bib/references.bib
csl: ../../static/bib/chicago-fullnote-bibliography-no-bib.csl
---

# Required

***Important***: The PDFs are posted on Learning Suite.

- <i class="far fa-file-pdf"></i> Chapter 8 in Jonathan Gruber, *Public Finance and Public Policy* [@Gruber:2005]
- <i class="fab fa-youtube"></i> Stephen Colbert, ["The Wørd—Priceless,"](http://www.cc.com/video-clips/e8zxmm/the-colbert-report-the-word---priceless)^[He's kinda wrong here, btw.] July 14, 2008
- <i class="fas fa-external-link-square-alt"></i> David Evans, ["What The Martian teaches us about the value of a statistical life"](https://blogs.worldbank.org/publicsphere/voices/what-martian-teaches-us-about-value-statistical-life), *People, Spaces, Deliberation,* The World Bank, October 2, 2015
- <i class="fas fa-external-link-square-alt"></i> Amy Gallo, ["A Refresher on Net Present Value,"](https://hbr.org/2014/11/a-refresher-on-net-present-value) *Harvard Business Review,* November 19, 2014
- <i class="far fa-file-pdf"></i> Dina Pomeranz, "Impact Evaluation Methods in Public Economics" [@Pomeranz:2017]
- <i class="far fa-file-pdf"></i> Gordon C. S. Smith and Jill P. Pell, "Parachute Use to Prevent Death and Major Trauma Related to Gravitational Challenge: Systematic Review of Randomised Controlled Trials" [@SmithPell:2003]
- <i class="far fa-file-pdf"></i> Yeh, Robert W., Linda R. Valsdottir, Michael W. Yeh, Changyu Shen, Daniel B. Kramer, Jordan B. Strom, Eric A. Secemsky, et al, "Parachute Use to Prevent Death and Major Trauma When Jumping From Aircraft: Randomized Controlled Trial" [@YehValsdottirYeh:2018]
